apiVersion: v1
kind: Service
metadata:
  name: {{ include "picpay-app.fullname" . }}
  labels:
    {{- include "picpay-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "picpay-app.selectorLabels" . | nindent 4 }}
